Vagrant.configure("2") do |config|
  # Enable and configure hostmanager plugin for managing host entries.
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20211001.0.5"

  # Define a reusable configuration for network and resources.
  def configure_node(node, private_ip, memory, cpus, bridge)
      node.vm.network "private_network", ip: private_ip
      node.vm.network "public_network", bridge: bridge
      node.vm.provider "virtualbox" do |vb|
          vb.memory = memory
          vb.cpus = cpus
      end
  end

  # Shared bridge setting
  bridge_name = "en0: Wi-Fi (AirPort)"

  # Configuration for the master node (k8s-node-1).
  config.vm.define "k8s-node-1" do |node01|
      configure_node(node01, "192.168.33.17", 1500, 2, bridge_name)
  end

  # Configuration for the second node (k8s-node-2).
  config.vm.define "k8s-node-2" do |node02|
      configure_node(node02, "192.168.33.18", 2000, 2, bridge_name)
  end

  # Configuration for the third node (k8s-node-3).
  config.vm.define "k8s-node-3" do |node03|
      configure_node(node03, "192.168.33.19", 2500, 2, bridge_name)
  end
end
